name: camera_web_integration_tests
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  camera_platform_interface: ^2.1.0
  camera_web:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  async: ^2.5.0
  cross_file: ^0.3.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: 0.3.0

# FOR TESTING AND INITIAL REVIEW ONLY. DO NOT MERGE.
# See https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changing-federated-plugins
dependency_overrides:
   {camera_platform_interface: {path: ../../../camera/camera_platform_interface}}
